### ISSUE TITLE
flutter_dialogflow_web: ^0.0.1 dependencies download not working

### ISSUE THREAD

**Issue by ganeshchenniah** [VictorRancesCode/flutter_dialogflow_web#1]
Running "flutter pub upgrade" in test_2...                      
Because every version of flutter_dialogflow_web depends on flutter_web from git which depends on flutter_web_ui any, every version of flutter_dialogflow_web requires flutter_web_ui from hosted.

So, because test2 depends on flutter_dialogflow_web ^0.0.1 which depends on flutter_web_ui from git, version solving failed.
pub upgrade failed (1; So, because test2 depends on flutter_dialogflow_web ^0.0.1 which depends on flutter_web_ui from git, version solving failed.)
Process finished with exit code 1

**Comment by sarat12us** [comment]
```
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```
